name: WhitelistPlugin
version: 1.0
main: com.example.whitelistplugin.WhitelistPlugin
api-version: 1.21
commands:
  safeCords:
    description: Speichert deine Aktuellen Koordinaten mit deiner Beschreibung
    usage: /safeCords <accesslevel> <Name des Ortes>
  showCords:
    description: Zeigt einem Spieler gespeicherte Koordinaten an
    usage: /showCords <accesslevel>
  deletePrivateCords:
    description: Löscht die Koordinaten die diese Beschreibung haben
    usage: /deletePrivateCords <Name des Ortes>