name: WhitelistPlugin
version: 1.0
main: com.example.whitelistplugin.WhitelistPlugin
api-version: 1.20
commands:
  safeCords:
    description: Speichert deine Aktuellen Koordinaten mit deiner Beschreibung
    usage: /safeCords <text>
