name: WhitelistPlugin
version: 1.0
main: com.example.whitelistplugin.WhitelistPlugin
api-version: 1.21
commands:
  safeCords:
    description: Speichert deine Aktuellen Koordinaten mit deiner Beschreibung
    usage: /safeCords <accesslevel> <Name des Ortes>
  showCords:
    description: Zeigt einem Spieler gespeicherte Koordinaten an
    usage: /showCords <accesslevel>
  deletePrivateCords:
    description: Löscht die Koordinaten die diese Beschreibung haben
    usage: /deletePrivateCords <Name des Ortes>
  editPrivateCords:
    description: Ändert den alten Namen zu einem neuen
    usage: /editPrivateCords <alter Name> <neuer Name>
  deletePublicCords:
    description: Löscht die Koordinaten die diese Beschreibung haben
    usage: /deletePublicCords <Name des Ortes>
    permission: coords.delete
permissions:
  coords.delete:
    description: Erlaubt das Löschen von gespeicherten Koordinaten
    default: op